### ISSUE TITLE
"cannot find a supported version of libgnutls on this system" error when starting

### ISSUE THREAD

**Issue by sergani** [AGProjects/mediaproxy#4]
Hello,

I'm running python2.7, and installed all required packages on a Centos 6.8 machine, however, I get the following errors when trying to start the server:
```python
[root@localhost mediaproxy-master]# python2.7 /usr/bin/media-relay --no-fork
Starting MediaProxy Relay 2.6.3
fatal error: failed to create MediaProxy Relay: cannot find a supported version of libgnutls on this system
[root@localhost mediaproxy-master]# python2.7 /usr/bin/media-dispatcher --no-fork
Starting MediaProxy Dispatcher 2.6.3
Traceback (most recent call last):
  File "/usr/bin/media-dispatcher", line 47, in <module>
    from mediaproxy.dispatcher import Dispatcher
  File "/usr/local/lib/python2.7/site-packages/mediaproxy/dispatcher.py", line 18, in <module>
    from gnutls.interfaces.twisted import TLSContext
  File "/usr/local/lib/python2.7/site-packages/gnutls/interfaces/twisted/__init__.py", line 13, in <module>
    from gnutls.connection import ClientSession, ServerSession, ServerSessionFactory
  File "/usr/local/lib/python2.7/site-packages/gnutls/connection.py", line 13, in <module>
    from gnutls.constants import *
  File "/usr/local/lib/python2.7/site-packages/gnutls/constants.py", line 21, in <module>
    from gnutls.library import constants
  File "/usr/local/lib/python2.7/site-packages/gnutls/library/__init__.py", line 58, in <module>
    libgnutls = load_library(abi_versions=(28, 30))  # will use the highest of the available ABI versions
  File "/usr/local/lib/python2.7/site-packages/gnutls/library/__init__.py", line 55, in load_library
    raise RuntimeError('cannot find a supported version of libgnutls on this system')
RuntimeError: cannot find a supported version of libgnutls on this system
```

Any thoughts?

Thanks
//M

**Comment by saghul** [comment]
You need to install all dependencies.  That includes libgnutls >= 3.1.4, which you don't seem to have.
